spring:
  application:
    name: taskmanager

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=taskmanager;trustServerCertificate=true
    username: sa
    password: atalu25h61
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true